on:
  push:
    tags:
      - 'v*'
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          lfs: true
          submodules: true
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Get tag
        shell: bash
        id: tag
        run: |
          tag="${{ github.ref_name }}"
          tag="${tag:1}"
          echo "out=untitled-game-system-manager-${tag}" >> $GITHUB_OUTPUT
      - name: Create archive
        shell: bash
        run: |
          rm -rf .git/
          cd IncusBindings && go mod vendor && cd ..
          ttar cfJ ${{ steps.tag.outputs.out }}.tar.xz . --transform "s,^,${{ steps.tag.outputs.tag }}/," * || echo "Might have failed"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Check our discord for patch notes: https://discord.gg/4kyWu2Vu
            More on what is done this month can be found on the latest newsletter entry: https://madladsquad.com/#monthly-newsletter
          draft: false
          prerelease: false
          files: ${{ steps.tag.outputs.out }}.tar.xz
          generate_release_notes: false
